[project]
name = "ordal-filkom"
version = "0.1.0"
description = "Chatbot RAG untuk dokumen akademik FILKOM"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    # LlamaIndex & RAG
    "llama-index",
    "llama-index-llms-groq",
    "llama-index-vector-stores-pinecone",
    "PyMuPDF",
    # Vector database
    "pinecone",
    # UI
    "streamlit",
    # Utils
    "python-dotenv",
]

[tool.uv]
package = false

[dependency-groups]
ingest = [
    "pymupdf4llm==1.28.2",
]
